# Generated by Django 6.0.3 on 2026-03-22 18:18

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ('fecha', 'hora', 'titulo'), 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ('-fecha_reserva',), 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AddField(
            model_name='evento',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default=api.models.generar_codigo_reserva, editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('obra', 'Obra de teatro'), ('musical', 'Musical'), ('recital', 'Recital'), ('ballet', 'Ballet'), ('concierto', 'Concierto'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
